spring:
  data:
    mongodb:
      uri: mongodb://test:123456@192.168.181.129:27017/testdb
#
#druid:
#  url: jdbc:mysql://192.168.181.129:3306/evtape_egame?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useSSL=false
#  #  url: jdbc:mysql://rm-uf6bbzxvwu9y85o97mo.mysql.rds.aliyuncs.com:3306/evtape_new?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useSSL=false
#  username: root
#  password: 123
#  driver-class-name: com.mysql.jdbc.Driver
#  initialSize: 5
#  minIdle: 5
#  maxActive: 10
#  timeBetweenEvictionRunsMillis: 60000
#  minEvictableIdleTimeMillis: 300000
#  validationQuery: select '1+1'
#  testWhileIdle: true

logging:
  level:
    com.dy.bulletscreen: DEBUG
  config: classpath:logback-local.xml